#=======================================================================================================================================
# PUNTO ACTIVO
#=======================================================================================================================================

#QA
app.env=QA
server.port = 8082
spring.datasource.url=jdbc:mysql://localhost:3306/generador_punto_activo_qa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin12345
#===>BUSINESSRULES PARA ESTAFETA<===
estafeta.restservice.br.beforesend=
#===>BUSINESSRULES PARA FEDEX<===
fedex.webservice.br.beforesend=com.xcustom.puntoactivo.businessrules.SetAccount
fedex.webservice.br.aftersend=com.xcustom.puntoactivo.businessrules.SaveResponse
fedex.restservice.br.beforesend=com.xcustom.puntoactivo.businessrules.SetAccountAlgoritmoRentabilidad