app.env=QA
server.port = 8082

#Conexion Servidor Reportes 1
spring.datasource.url=jdbc:mysql://20.114.119.138:3306/guias_qa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=R3portes

app.estafeta.path=/home/gRootUser/GuiasQA/EstafetaPDF/

#===>BUSINESSRULES PARA ESTAFETA<===
estafeta.restservice.br.beforesend=\
com.xcustom.alan.businessrules.ValidateUserConfiguration,\
com.xcustom.alan.businessrules.SetAccount,\
com.xcustom.alan.businessrules.ChangeInformation,\
com.xcustom.alan.businessrules.GetService,\
com.xcustom.alan.businessrules.SetReexpedicion,\
com.xcustom.alan.businessrules.ParseServiceType,\
com.xcustom.alan.businessrules.SetLabelPath,\
com.xcustom.alan.businessrules.GetAliasAccount\

#===>BUSINESSRULES PARA FEDEX<===
fedex.webservice.br.beforesend=
fedex.webservice.br.aftersend=
fedex.restservice.br.beforesend=
spring.datasource.hikari.max-idle-time=1800000
spring.datasource.hikari.minimum-idle=5