application.title=Integrador MicroService
application.version=3.8
logging.level.root=INFO
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

#integrador.app=local/
integrador.app=alan/qa/
#integrador.app=alan/prd/

#integrador.app=sentpack/qa/


# Importante para el caso de sadalv eliminar las siguientes clases en caso de marcar error: 
# Estas son clases que apuntan a la db de alan con diferentes columnas que sadalv.
# com.integrador.repositories.UsuarioAlanRepository
# com.integrador.repositories.UsuarioAlan
# com.integrador.repositories.ConfiguracionRepository
# com.integrador.models.Configuracion