#=======================================================================================================================================
# Alan
#=======================================================================================================================================

#PRD
app.env=PRD
server.port = 8081
spring.datasource.url=jdbc:mysql://40.124.112.231:8606/guias?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&autoReconnect=true
spring.datasource.username=root
spring.datasource.password=G3n3r@d0r_d3_Gu1@5_v2_567qaz

app.estafeta.path=/home/gRootUser/Guias/EstafetaPDF/

#===>BUSINESSRULES PARA ESTAFETA<===
estafeta.restservice.br.beforesend=\
com.xcustom.alan.businessrules.ValidateUserConfiguration,\
com.xcustom.alan.businessrules.SetAccount,\
com.xcustom.alan.businessrules.ChangeInformation,\
com.xcustom.alan.businessrules.GetService,\
com.xcustom.alan.businessrules.SetReexpedicion,\
com.xcustom.alan.businessrules.ParseServiceType,\
com.xcustom.alan.businessrules.SetLabelPath,\
com.xcustom.alan.businessrules.GetAliasAccount\

#===>BUSINESSRULES PARA FEDEX<===
fedex.webservice.br.beforesend=
fedex.webservice.br.aftersend=
fedex.restservice.br.beforesend=
spring.datasource.hikari.max-idle-time=1800000
spring.datasource.hikari.minimum-idle=5
