#=======================================================================================================================================
# ALAN
#=======================================================================================================================================

#Local - Mac
app.env=QA
server.port = 8082

#localhost
spring.datasource.url=jdbc:mysql://localhost:3306/guias?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin12345

app.estafeta.path=/Users/jesussilva/Documents/Temp/Alan/GuiasApp/Estafeta/

#QA
#spring.datasource.url=jdbc:mysql://20.114.119.138:3306/guias_qa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=R3portes

#spring.datasource.url=jdbc:mysql://40.124.112.231:8606/guias?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&autoReconnect=true
#spring.datasource.username=root
#spring.datasource.password=G3n3r@d0r_d3_Gu1@5_v2_567qaz


#===>BUSINESSRULES PARA ESTAFETA<===
estafeta.restservice.br.beforesend=\
com.xcustom.alan.businessrules.ValidateUserConfiguration,\
com.xcustom.alan.businessrules.SetAccount,\
com.xcustom.alan.businessrules.ChangeInformation,\
com.xcustom.alan.businessrules.GetService,\
com.xcustom.alan.businessrules.SetReexpedicion,\
com.xcustom.alan.businessrules.ParseServiceType,\
com.xcustom.alan.businessrules.SetLabelPath,\
com.xcustom.alan.businessrules.GetAliasAccount\


#===>BUSINESSRULES PARA FEDEX<===
fedex.webservice.br.beforesend=
fedex.webservice.br.aftersend=
fedex.restservice.br.beforesend=

#Local - Windows
#app.env=QA
#server.port = 8081
#spring.datasource.url=jdbc:mysql://localhost:3306/guias?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin
#===>BUSINESSRULES PARA ESTAFETA<===
#estafeta.restservice.br.beforesend=com.xcustom.alan.businessrules.SetAccount
#===>BUSINESSRULES PARA FEDEX<===
#fedex.webservice.br.beforesend=
#fedex.webservice.br.aftersend=
#fedex.restservice.br.beforesend=




#=======================================================================================================================================
# SADALV
#=======================================================================================================================================

#Local - Windows
#app.env=QA
#server.port = 8081
#spring.datasource.url=jdbc:mysql://localhost:3306/generador_sadalv?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin
#===>BUSINESSRULES PARA ESTAFETA<===
#estafeta.restservice.br.beforesend=
#===>BUSINESSRULES PARA FEDEX<===
#fedex.webservice.br.beforesend=
#fedex.restservice.br.beforesend=

#Local - Mac
#app.env=QA
#server.port = 8082
#spring.datasource.url=jdbc:mysql://localhost:3306/generador_sadalv?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin12345
#===>BUSINESSRULES PARA ESTAFETA<===
#estafeta.restservice.br.beforesend=com.xcustom.sadalv.businessrules.SetAccount
#===>BUSINESSRULES PARA FEDEX<===
#fedex.webservice.br.beforesend=
#fedex.webservice.br.aftersend=
#fedex.restservice.br.beforesend=




#=======================================================================================================================================
# Punto activo
#=======================================================================================================================================

#Local - Mac
#app.env=QA
#server.port = 8082
#spring.datasource.url=jdbc:mysql://localhost:3306/generador_punto_activo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin12345
#===>BUSINESSRULES PARA ESTAFETA<===
#estafeta.restservice.br.beforesend=
#===>BUSINESSRULES PARA FEDEX<===
#fedex.webservice.br.beforesend=com.xcustom.puntoactivo.businessrules.SetAccount
#fedex.webservice.br.aftersend=com.xcustom.puntoactivo.businessrules.SaveResponse
#fedex.restservice.br.beforesend=com.xcustom.puntoactivo.businessrules.SetAccountAlgoritmoRentabilidad

#=======================================================================================================================================
# Enviemoslo
#=======================================================================================================================================
#Local - Mac
#app.env=QA
#server.port = 8082
#spring.datasource.url=jdbc:mysql://localhost:3306/generador_enviemoslo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=admin12345
#===>BUSINESSRULES PARA ESTAFETA<===
#estafeta.restservice.br.beforesend=com.xcustom.enviemoslo.businessrules.SetAccount
#===>BUSINESSRULES PARA FEDEX<===
#fedex.webservice.br.beforesend=
#fedex.webservice.br.aftersend=
#fedex.restservice.br.beforesend=