#=======================================================================================================================================
# SADALV
#=======================================================================================================================================

#QA
app.env=QA
server.port = 8082
spring.datasource.url=jdbc:mysql://localhost:3306/generador_enviemoslo_qa?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin12345

app.estafeta.path=

#===>BUSINESSRULES PARA ESTAFETA<===
estafeta.restservice.br.beforesend=com.xcustom.enviemoslo.businessrules.SetAccount

#===>BUSINESSRULES PARA FEDEX<===
fedex.webservice.br.beforesend=
fedex.webservice.br.aftersend=
fedex.restservice.br.beforesend=
